### ISSUE TITLE
Why `company` :defer 5 ?

### ISSUE THREAD

**Issue by FirstLoveLife** [jwiegley/dot-emacs#18]
https://github.com/jwiegley/dot-emacs/blob/master/init.el#L737

I cannot figure out any reason. 
Thx.

**Comment by jwiegley** [comment]
Without `:defer 5`, company is delayed until I use one of the listed commands. The purpose of this setting is to cause it to be loaded no matter what after the first five seconds of idle time. I use this on a ton of packages, so that loading is super quick (which can be useful in certain debugging scenario), but after 5 seconds I get all the packages.
